<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /home/fiveyyyy/github/upagraha/static/models/satellite_low_poly.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/satellite_low_poly.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0.31, 4.27, -1.04]} scale={10.61}>
      <T.Mesh
        geometry={gltf.nodes.Battery_Shield_v20_Component21_Placa1_Body2001_Default00.geometry}
        material={gltf.nodes.Battery_Shield_v20_Component21_Placa1_Body2001_Default00.material}
        position={[-0.07, 0.01, 0.1]}
        rotation={[1.59, -0.34, 0.56]}
        scale={1.29}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.magnetometer_2_handle.geometry}
      material={gltf.nodes.magnetometer_2_handle.material}
      position={[0.42, 3.63, -0.03]}
      rotation={[-0.19, -0.52, 1.17]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes['mid_panel-2'].geometry}
      material={gltf.nodes['mid_panel-2'].material}
      position={[-1.33, 4.37, -0.76]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.payload_lens.geometry}
      material={gltf.nodes.payload_lens.material}
      position={[0.75, 3.59, 0.68]}
      rotation={[-2.63, -0.93, -2.55]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.side_panel.geometry}
      material={gltf.nodes.side_panel.material}
      position={[0.06, 3.65, 0.26]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.thin_panel_1.geometry}
      material={gltf.nodes.thin_panel_1.material}
      position={[-1.58, 6.91, -2.34]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.thin_panel_2.geometry}
      material={gltf.nodes.thin_panel_2.material}
      position={[-0.29, 3.99, -0.09]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.MCU_1.geometry}
      material={gltf.nodes.MCU_1.material}
      position={[0.65, 3.76, 0.29]}
      rotation={[-0.19, -0.52, -0.4]}
      scale={[0.12, 0.17, 0.13]}
    />
    <T.Mesh
      geometry={gltf.nodes.MCU_2.geometry}
      material={gltf.nodes.MCU_2.material}
      position={[0.48, 3.82, 0.57]}
      rotation={[-0.19, -0.52, -0.4]}
      scale={[0.12, 0.17, 0.13]}
    />
    <T.Mesh
      geometry={gltf.nodes.magnetorquer_1.geometry}
      material={gltf.nodes.magnetorquer_1.material}
      position={[0.66, 3.88, 0.08]}
      rotation={[-0.19, -0.52, -1.97]}
      scale={[0.02, 0.01, 0.02]}
    />
    <T.Mesh
      geometry={gltf.nodes.magnetorquer_2.geometry}
      material={gltf.nodes.magnetorquer_2.material}
      position={[0.97, 4.23, -0.17]}
      rotation={[-2.63, -0.93, 2.17]}
      scale={[0.02, 0.01, 0.02]}
    />
    <T.Mesh
      geometry={gltf.nodes.battery_holder.geometry}
      material={gltf.nodes.battery_holder.material}
      position={[-0.48, 4.14, -0.59]}
      rotation={[1.59, -0.34, 2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.battery_screws.geometry}
      material={gltf.nodes.battery_screws.material}
      position={[-0.48, 4.14, -0.59]}
      rotation={[1.59, -0.34, 2.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.payload_body.geometry}
      material={gltf.nodes.payload_body.material}
      position={[0.75, 3.59, 0.68]}
      rotation={[-2.63, -0.93, -2.55]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.payload_pins.geometry}
      material={gltf.nodes.payload_pins.material}
      position={[0.75, 3.59, 0.68]}
      rotation={[-2.63, -0.93, -2.55]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.magnetometer_2001.geometry}
      material={gltf.nodes.magnetometer_2001.material}
      position={[0.42, 3.63, -0.03]}
      rotation={[-0.19, -0.52, 1.17]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.magnetometer_1_handle.geometry}
      material={gltf.nodes.magnetometer_1_handle.material}
      position={[-0.05, 3.89, 0.52]}
      rotation={[0.51, 0.93, 0.97]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.magnetometer_2004.geometry}
      material={gltf.nodes.magnetometer_2004.material}
      position={[-0.05, 3.89, 0.52]}
      rotation={[0.51, 0.93, 0.97]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.solar_panels_right.geometry}
      material={gltf.nodes.solar_panels_right.material}
      position={[0.58, 4.37, -1.01]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={-0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.solar_cells_right.geometry}
      material={gltf.nodes.solar_cells_right.material}
      position={[0.61, 4.36, -1.05]}
      rotation={[-1.55, 0.34, 1.01]}
      scale={-0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.solar_panels_left.geometry}
      material={gltf.nodes.solar_panels_left.material}
      position={[-0.59, 4.76, 1]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={-0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.solar_cells_left.geometry}
      material={gltf.nodes.solar_cells_left.material}
      position={[-0.59, 4.76, 1]}
      rotation={[-1.55, 0.34, -2.13]}
      scale={-0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.top_panel.geometry}
      material={gltf.nodes.top_panel.material}
      position={[0.36, 4.46, 0.18]}
      rotation={[0.51, 0.93, 2.55]}
      scale={-0.18}
    />
    <T.Mesh
      geometry={gltf.nodes.payload_knob.geometry}
      material={gltf.nodes.payload_knob.material}
      position={[0.75, 3.59, 0.68]}
      rotation={[-2.63, -0.93, -2.55]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.battery_plate.geometry}
      material={gltf.nodes.battery_plate.material}
      position={[-0.58, 4.18, -0.41]}
      rotation={[1.59, -0.34, 2.13]}
      scale={0.4}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
