<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /home/fiveyyyy/github/upagraha/static/models/satellite.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { onMount } from 'svelte';

  export const ref = new Group()

  const gltf = useGltf('/models/satellite.glb', { useDraco: true})

  const component = forwardEventHandlers()

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-0.6, 0.73, -0.32]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01}>
      <T.Mesh geometry={gltf.nodes.Mesh011.geometry} material={gltf.materials['battery_holder.004']} />
      <T.Mesh geometry={gltf.nodes.Mesh011_1.geometry} material={gltf.materials.battery_cells} />
      <T.Mesh geometry={gltf.nodes.Mesh011_2.geometry} material={gltf.materials['battery_holder.008']} />
      <T.Mesh geometry={gltf.nodes.Mesh011_3.geometry} material={gltf.materials.side_panels} />
      <T.Mesh geometry={gltf.nodes.Mesh011_4.geometry} material={gltf.materials.batter_pcb_plate} />
    </T.Group>
    <T.Group position={[0.26, 0.66, 0.47]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.01}>
      <T.Mesh geometry={gltf.nodes.Magnetometer001.geometry} material={gltf.materials['body.002']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer001_1.geometry} material={gltf.materials['pins_holder.002']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer001_2.geometry} material={gltf.materials['pins.005']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer001_3.geometry} material={gltf.materials['holder.002']} />
    </T.Group>
    <T.Group position={[0.4, 0.66, -0.27]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.01}>
      <T.Mesh geometry={gltf.nodes.Magnetometer002.geometry} material={gltf.materials['body.002']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer002_1.geometry} material={gltf.materials['pins_holder.002']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer002_2.geometry} material={gltf.materials['pins.005']} />
      <T.Mesh geometry={gltf.nodes.Magnetometer002_3.geometry} material={gltf.materials['holder.002']} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes['mid_panel-2'].geometry}
      material={gltf.materials['side_panels.001']}
      position={[-1.44, 0.66, 0]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.01}
    />
    <T.Group position={[1.21, 0.64, 0.06]} rotation={[0, -1.57, 0]} scale={0.01}>
      <T.Mesh geometry={gltf.nodes.Payload001.geometry} material={gltf.materials['Material.007']} />
      <T.Mesh geometry={gltf.nodes.Payload001_1.geometry} material={gltf.materials['pins.002']} />
      <T.Mesh geometry={gltf.nodes.Payload001_2.geometry} material={gltf.materials['pin_holders.001']} />
      <T.Mesh geometry={gltf.nodes.Payload001_3.geometry} material={gltf.materials['lens.001']} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.side_panel.geometry}
      material={gltf.materials['side_panels.001']}
      position={[0.42, 0.46, 0.06]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.thin_panel_1.geometry}
      material={gltf.materials['side_panels.001']}
      position={[-3.21, 2.94, -0.8]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.thin_panel_2.geometry}
      material={gltf.materials['side_panels.001']}
      position={[-0.14, 0.66, -0.01]}
      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials.imu_cube}
      position={[0.87, 0.77, -0.19]}
      scale={[0.12, 0.17, 0.13]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials.imu_cube}
      position={[0.87, 0.77, 0.14]}
      scale={[0.12, 0.17, 0.13]}
    />
    <T.Mesh
      geometry={gltf.nodes['magnetorquer_1(stl)'].geometry}
      material={gltf.materials['pin_holders.001']}
      position={[0.74, 0.88, -0.35]}
      rotation={[0, 0, -Math.PI / 2]}
      scale={[0.02, 0.01, 0.02]}
    />
    <T.Mesh
      geometry={gltf.nodes['magnetorquer_1(stl)001'].geometry}
      material={gltf.materials['pin_holders.001']}
      position={[0.76, 1.31, -0.66]}
      rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      scale={[0.02, 0.01, 0.02]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
