<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.2 /home/fiveyyyy/github/upagraha/static/models/scene.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group, MeshStandardMaterial, ShaderMaterial } from 'three'
  import { T, forwardEventHandlers, useFrame } from '@threlte/core'
  import { useGltf, Float, Edges } from '@threlte/extras'
  import animate from 'animejs';

  export const ref = new Group()
  let sputnikSolarCellsRef = null;
  let checkRef = null;
  let starsRef1 = null;
  let starsRef2 = null;
  let shootingStarEmissionRef = null;
  let sputnikRef = null;

  useFrame((_, delta) => {
    if (sputnikSolarCellsRef) {
      sputnikSolarCellsRef.material.uniforms.uTime.value += delta
    }
    if (starsRef1) {
      starsRef1.rotation.z += 0.0005;
    }
    if (starsRef2) {
      starsRef2.rotation.z -= 0.0005;
    }
    if (shootingStarEmissionRef) {
      shootingStarEmissionRef.material.uniforms.uTime.value += delta
    }
    if (sputnikRef) {
      // sputnikRef.rotation.z += 0.003;
    }
  })

  const gltf = useGltf('/models/scene.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}

    <!-- Sixth Plane and Fifth Plane are interchanged Typo..... -->
    <T.Group scale={2.4}>
      <T.Mesh name="sixth_plane" geometry={gltf.nodes.sixth_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#011b35">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="fifth_plane" geometry={gltf.nodes.fifth_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#001222">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="fourth_plane" geometry={gltf.nodes.fourth_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#002341">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="third_plane" geometry={gltf.nodes.third_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#00315b">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="second_plane" geometry={gltf.nodes.second_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#003d72">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="first_plane" geometry={gltf.nodes.first_plane.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#014d8f">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh visible={false} name="scene_cube" geometry={gltf.nodes.scene_cube.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#000000">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>
    </T.Group>

    <T.Group>
      <T.Mesh name="shooting_star" geometry={gltf.nodes.shooting_star.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#0000ff">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh
        name="shooting_star_trajectory"
        geometry={gltf.nodes.shooting_star_trajectory.geometry}
      >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#ac2626">
        </T.MeshStandardMaterial>
        <Edges transparent={true} opacity={0.0}  visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh
        name="shooting_star_emission"
        geometry={gltf.nodes.shooting_star_emission.geometry}
        bind:ref={shootingStarEmissionRef}
      >
        <T.ShaderMaterial
          transparent
          uniforms={{
            uTime: { value: 0 }
          }}
          vertexShader={`
          varying vec2 vUv;
          void main() {
          vUv = uv;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`}
          fragmentShader={`
          varying vec2 vUv;
          uniform float uTime;
          void main() {
          vec2 newUv = vUv;
          vec3 final = vec3(sin(length(newUv * 10.0 + uTime * 1.25)));
          final = pow(final, vec3(2.0));
          vec3 color = vec3(8.0, 0.4, 0.4);
          color *= final; 
          gl_FragColor = vec4(color, final.r);
}
`}
        />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
    </T.Group>


    <T.Mesh name="saturn_ring" geometry={gltf.nodes.saturn_ring.geometry}>
      <T.ShaderMaterial
        transparent={true} 
        opacity={1.0}
        vertexShader={`
        varying vec2 vUv;
          void main() {
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
      `}
        fragmentShader={`
        varying vec2 vUv;
        void main() {
          vec3 final = vec3(sin(length(gl_FragCoord / 1800.0) * 300.0));
          gl_FragColor = vec4(final, 1.0);
        }
      `}
      />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
    </T.Mesh>

    <T.Mesh name="planet_four" geometry={gltf.nodes.plane_four.geometry}>
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#6b0404">
      </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="#6b0404" />
    </T.Mesh>

    <T.Mesh name="planet_two" geometry={gltf.nodes.plane_two.geometry}>
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#351747">
      </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
    </T.Mesh>

    <T.Mesh name="planet_three" geometry={gltf.nodes.planet_three.geometry}>
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#103b39">
      </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
    </T.Mesh>
    
    <T.Mesh name="planet_one" geometry={gltf.nodes.planet_one.geometry}>
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#04435a">
      </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
    </T.Mesh>

      
    <T.Mesh name="planet_five" geometry={gltf.nodes.planet_five.geometry}>
        <T.ShaderMaterial 
          transparent={true} 
          opacity={1.0}
        fragmentShader={`
        void main() {
        vec3 final = vec3(sin(length( gl_FragCoord / 400.0) * 100.0));
        final = pow(final, vec3(2.0));
        vec3 color = vec3(1.0, 2.0, 3.0);
        gl_FragColor = vec4(color * final, 1.0);
        }
        `}
        />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
    </T.Mesh>

<!-- Discovery -->
    <Float
      floatIntensity={4}
      floatingRange={[-0.1, 0.1]}
      speed={3}
    >
    <T.Group scale={3}>
      <T.Mesh name="discovery_emission_1" geometry={gltf.nodes.discovery_emission.geometry}>
       <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#fffff">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="discovery_emission_2" geometry={gltf.nodes.discovery_emission.geometry} scale={1.2}
          position={[0, -0.048, 0.035]}
        >
          <T.ShaderMaterial 
            transparent={true} 
            opacity={1.0}
            uniforms={{
              uTime: { value: 0 }
            }}
            vertexShader={`
            varying vec2 vUv;
            void main() {
              vUv = uv;
              gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
            }
`}
            fragmentShader={`
            varying vec2 vUv;
            uniform float uTime;
            void main() {
              vec2 newUv = vUv;
              vec3 variationX = vec3(sin(length(newUv.x) * 80.0));
              vec3 variationY = vec3(sin(length(newUv.y + uTime * 0.08) * 80.0));
              vec3 final = vec3(step(0.1, variationX * variationY));
              vec3 color = vec3(3.0, 0.0, 0.0);
              color.r = sin(color.r * 0.5);
              final = pow(final, vec3(2.0));
              vec3 finalColor = color * final;
              gl_FragColor = vec4(finalColor, color.r);
            }
`}
          />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="discovery_propeller_emission_1" geometry={gltf.nodes.propeller_emission.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#fffff">
          </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="discovery_propeller_emission_2" geometry={gltf.nodes.propeller_emission.geometry} scale={1.01} position={[0, 0, 0.01]}>
         <T.ShaderMaterial 
            transparent={true}
            opacity={1.0}
            uniforms={{
              uTime: { value: 0 }
            }}
            vertexShader={`
            varying vec2 vUv;
            void main() {
              vUv = uv;
              gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
            }
`}
            fragmentShader={`
            varying vec2 vUv;
            uniform float uTime;
            void main() {
              vec2 newUv = vUv;
              vec3 variationX = vec3(sin(length(newUv.x) * 80.0));
              vec3 variationY = vec3(sin(length(newUv.y + uTime * 0.08) * 80.0));
              vec3 final = vec3(step(0.1, variationX * variationY));
              vec3 color = vec3(3.0, 0.0, 0.0);
              color.r = sin(color.r * 0.5);
              final = pow(final, vec3(2.0));
              vec3 finalColor = color * final;
              gl_FragColor = vec4(finalColor, 0.5);
            }
`}
          />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="discovery_black_body" geometry={gltf.nodes.discovery_black_body.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#000000">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="discovery_white_body" geometry={gltf.nodes.discovery_white_body.geometry}>
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#727272">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
      
      <T.Mesh
        name="discovery_propeller_orange_shaft"
        geometry={gltf.nodes.propeller_orange_shaft.geometry}
      >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#6d2e00">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh
        name="discovery_propeller_yellow_tanks"
        geometry={gltf.nodes.propeller_yellow_tanks.geometry}
      >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#805504">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
    </T.Group>
    </Float>

<!-- Sputnik -->
    <T.Group 
      position={[-0.2, 0, 0]}
      bind:ref={sputnikRef}>
      <T.Mesh name="sputnik_black_body" geometry={gltf.nodes.sputnik_black_body.geometry} 
        position={[0, 0, 0]}
      >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#000000" />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="sputnik_white_body" geometry={gltf.nodes.sputnik_white_body.geometry} >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#696969">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>

      <T.Mesh name="sputnik_yellow_body" geometry={gltf.nodes.sputnik_yellow_body.geometry} >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#8c4b0f">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
      <T.Mesh name="cube" geometry={gltf.nodes.Cube.geometry} >
        <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#000000">
        </T.MeshStandardMaterial>
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
      <T.Mesh 
        name="sputnik_solar_cells"
        bind:ref={sputnikSolarCellsRef}
        geometry={gltf.nodes.Cube001.geometry}>
        <T.ShaderMaterial
          transparent={true} 
          opacity={1.0}
          uniforms={{
            uTime: { value: 0 }
          }}   
          vertexShader={`
          varying vec2 vUv;
          void main() {
            vUv = uv;
            gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
          }
          `}
          fragmentShader={`
          varying vec2 vUv;
          uniform float uTime;
          void main() {
            vec2 newUv = vUv;
            vec3 variationX = vec3(sin(length(newUv.x) * 80.0));
            vec3 variationY = vec3(sin(length(newUv.y + uTime * 0.08) * 80.0));
            vec3 final = vec3(step(0.1, variationX * variationY));
            vec3 color = vec3(1.0, 2.0, 3.0);
            color.r = sin(color.r * 0.5);
            final = pow(final, vec3(2.0));
            vec3 finalColor = color * final;
            gl_FragColor = vec4(finalColor, 1.0);
          }
          `}
        />
       <Edges transparent={true} opacity={0.0} visible={false} color="cyan" />
      </T.Mesh>
    </T.Group>

    <T.Mesh name="stars_1" geometry={gltf.nodes.stars.geometry}
    scale={1.5}
    bind:ref={starsRef2}
    >
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#6b7c02">
      </T.MeshStandardMaterial>
       <Edges color="cyan" />
    </T.Mesh>

    <T.Mesh name="stars_2" geometry={gltf.nodes.stars.geometry} 
    position={[1.5, 0, 0]}
    scale={2}
    bind:ref={starsRef1}
    >
      <T.MeshStandardMaterial transparent={true} opacity={1.0} color="#6b7c02">
      </T.MeshStandardMaterial>
       <Edges color="cyan" />
    </T.Mesh>

  {:catch error}

    <slot name="error" {error} />

  {/await}

  <slot {ref} />
</T>
