<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.2 /home/fiveyyyy/github/upagraha/static/models/scene.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group, MeshStandardMaterial, ShaderMaterial } from 'three'
  import { T, forwardEventHandlers, useFrame } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Sheet, SheetObject } from '@threlte/theatre';

  export const ref = new Group()
  let sputnikSolarCellsRef = null;
  let checkRef = null;

  useFrame((_, delta) => {
    if (sputnikSolarCellsRef) {
      sputnikSolarCellsRef.material.uniforms.uTime.value += delta
    }
    if (checkRef) {
    }
  })

  const gltf = useGltf('/models/scene.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} >
      <T.MeshStandardMaterial color="#000000">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh 
      bind:ref={sputnikSolarCellsRef}
      geometry={gltf.nodes.Cube001.geometry}>
      <T.ShaderMaterial
        uniforms={{
          uTime: { value: 0 }
        }}   
        vertexShader={`
        varying vec2 vUv;
        void main() {
          vUv = uv;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
        `}
        fragmentShader={`
        varying vec2 vUv;
        uniform float uTime;
        void main() {
          vec2 newUv = vUv;
          vec3 variationX = vec3(sin(length(newUv.x) * 80.0));
          vec3 variationY = vec3(sin(length(newUv.y + uTime * 0.08) * 80.0));
          vec3 final = vec3(step(0.1, variationX * variationY));
          vec3 color = vec3(1.0, 2.0, 3.0);
          color.r = sin(color.r * 0.5);
          final = pow(final, vec3(2.0));
          vec3 finalColor = color * final;
          gl_FragColor = vec4(finalColor, 1.0);
        }
        `}
      />
    </T.Mesh>
    <!-- Sixth Plane and Fifth Plane are interchanged Typo..... -->
    <T.Mesh geometry={gltf.nodes.sixth_plane.geometry}>
      <T.MeshStandardMaterial color="#011b35">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.fifth_plane.geometry}>
      <T.MeshStandardMaterial color="#001222">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.fourth_plane.geometry}>
      <T.MeshStandardMaterial color="#002341">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.third_plane.geometry}>
      <T.MeshStandardMaterial color="#00315b">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.second_plane.geometry}>
      <T.MeshStandardMaterial color="#003d72">
      </T.MeshStandardMaterial>
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.first_plane.geometry}>
      <T.MeshStandardMaterial color="#014d8f">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.scene_cube.geometry}>
      <T.MeshStandardMaterial color="#000000">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.shooting_star.geometry} material={gltf.nodes.shooting_star.material} />

    <T.Mesh
      geometry={gltf.nodes.shooting_star_trajectory.geometry}
      material={gltf.nodes.shooting_star_trajectory.material}
    />

    <T.Mesh
      geometry={gltf.nodes.shooting_star_emission.geometry}
      material={gltf.nodes.shooting_star_emission.material}
    />

    <T.Mesh geometry={gltf.nodes.saturn_ring.geometry}>
      <T.ShaderMaterial
        vertexShader={`
        varying vec2 vUv;
void main() {
gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`}
        fragmentShader={`
        varying vec2 vUv;
void main() {
vec3 final = vec3(sin(length(gl_FragCoord / 1800.0) * 300.0));
gl_FragColor = vec4(final, 1.0);
}
`}
      />
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.plane_two.geometry}>
      <T.MeshStandardMaterial color="#351747">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.planet_three.geometry}>
      <T.MeshStandardMaterial color="#103b39">
      </T.MeshStandardMaterial>
    </T.Mesh>
    
    <T.Mesh geometry={gltf.nodes.plane_four.geometry}>
      <T.MeshStandardMaterial color="#6b0404">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.planet_one.geometry}>
      <T.MeshStandardMaterial color="#04435a">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.planet_four_glow_cover.geometry}
    >
      <T.ShaderMaterial transparent
      fragmentShader={`
      void main() {
      gl_FragColor = vec4(0.9, 0.0, 0.0, 0.3);
}
`}
      />
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.planet_five.geometry}>
        <T.ShaderMaterial 
        
        fragmentShader={`
        void main() {
        vec3 final = vec3(sin(length( gl_FragCoord / 400.0) * 100.0));
        final = pow(final, vec3(2.0));
        vec3 color = vec3(1.0, 2.0, 3.0);
        
        gl_FragColor = vec4(color * final, 1.0);
        }
        `}
        />
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.discovery_emission.geometry} material={gltf.nodes.discovery_emission.material} />
    <T.Mesh geometry={gltf.nodes.propeller_emission.geometry} material={gltf.nodes.propeller_emission.material} />

    <T.Mesh geometry={gltf.nodes.discovery_black_body.geometry}>
      <T.MeshStandardMaterial color="#000000">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.discovery_white_body.geometry}>
      <T.MeshStandardMaterial color="#727272">
      </T.MeshStandardMaterial>
    </T.Mesh>
    
    <T.Mesh
      geometry={gltf.nodes.propeller_orange_shaft.geometry}
    >
      <T.MeshStandardMaterial color="#6d2e00">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.propeller_yellow_tanks.geometry}
    >
      <T.MeshStandardMaterial color="#805504">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.sputnik_black_body.geometry} >
      <T.MeshStandardMaterial color="#000000" />
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.sputnik_white_body.geometry} >
      <T.MeshStandardMaterial color="#696969">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.sputnik_yellow_body.geometry} >
      <T.MeshStandardMaterial color="#8c4b0f">
      </T.MeshStandardMaterial>
    </T.Mesh>

    <T.Mesh geometry={gltf.nodes.stars.geometry}>
      <T.MeshStandardMaterial color="#6b7c02">
      </T.MeshStandardMaterial>
    </T.Mesh>

  {:catch error}

    <slot name="error" {error} />

  {/await}

  <slot {ref} />
</T>
